### ISSUE TITLE
GPU-Enabled TensorFlow

### ISSUE THREAD

**Issue by RagingTiger** [RagingTiger/Omega-Notebook#59]
References:
+ https://www.tensorflow.org/install/docker
+ https://hub.docker.com/layers/tensorflow/tensorflow/2.12.0-gpu/images/sha256-ce32fe3c53f94938de1513b3fe5fa25aa655a2f4c4bced42cf598fb8ce911219?context=explore
+ https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.gpu
+ https://help.valohai.com/hc/en-us/articles/4421364087569-Build-your-own-Docker-image
+ https://github.com/anibali/docker-pytorch
+ https://github.com/docker/build-push-action
+ https://www.tensorflow.org/install/pip

**Comment by lafemmephile** [comment]
Implemented with: 3ee20e30507958701a601056ad42486b993accc9

**Comment by RagingTiger** [comment]
Implemented with: 3ee20e30507958701a601056ad42486b993accc9
